POST http://localhost:3000/login/ 
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}
###

POST http://localhost:3000/login/
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjY5MDkwODkzfQ.NcXv3RvMM2oKd_zlc-b1ntTV-JXTAZoDao_lI1a77eQ

###
GET http://localhost:3000/states/ 

###
GET http://localhost:3000/states/8/ 
Content-Type: application/json 

{
  "stateId": 8,
  "stateName": "Delhi",
  "population": 16787941
}

###

POST http://localhost:3000/districts/ 
Content-Type: application/json 

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###
GET http://localhost:3000/districts/322/
Content-Type: application/json 

{
  "districtId": 322,
  "districtName": "Palakkad",
  "stateId": 17,
  "cases": 61558,
  "cured": 59276,
  "active": 2095,
  "deaths": 177
}

###
DELETE  http://localhost:3000/districts/322/


####
PUT http://localhost:3000/districts/321/
Content-Type: application/json 

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###
GET http://localhost:3000/states/8/stats/
 Content-Type: application/json

{
  "totalCases": 724355,
  "totalCured": 615324,
  "totalActive": 99254,
  "totalDeaths": 9777
}



